select t1.PRODUCT_CODE as PRODUCT_CODE, sum(PRICE*SALES_AMOUNT) as SALES
from PRODUCT t1 inner join OFFLINE_SALE t2 on t1.PRODUCT_ID=t2.PRODUCT_ID
group by PRODUCT_CODE
order by SALES desc , PRODUCT_CODE