select YEAR(DIFFERENTIATION_DATE) as year,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE))
        - SIZE_OF_COLONY AS YEAR_DEV, ID
from ECOLI_DATA  
order by year, YEAR_DEV